### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by singlaabhinandan** [DNJha/IoTSim-Edge#1] opened 2020-02-25 18:22 UTC
Getting compilation errors, a few of the modules are not getting imported so I manually downloaded them and added the path to the project on Eclipse. Still encountering errors such as 
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.edge.examples.Example3.init(Example3.java:261)
	at org.edge.examples.Example3.main(Example3.java:695)

**Comment by DNJha** [comment] 2020-02-25 22:17
Hi Abhinandan,

There are two main reasons of error, first, mapping of CloudSim external jar file and second, lombok jar file. Just now I added the description about how to resolve these in the Readme file. Please try that and let me know if it does not work.

**Comment by singlaabhinandan** [comment] 2020-02-26 16:39
I did include both the files and added them to their respective paths.
PFA Screenshots,

**Comment by DNJha** [comment] 2020-02-26 17:22
I couldn't find any attachment. Please send me the screenshot. 

Also try to run an example and see if it is running, if not, please also send me that screenshot as well.

**Comment by singlaabhinandan** [comment] 2020-02-26 19:25
Please check the Screenshots.

**Comment by singlaabhinandan** [comment] 2020-02-26 19:33
PFA

**Comment by DNJha** [comment] 2020-02-26 19:35
I couldn't find any attachment. However based on your first message, I figured out that the main file cannot find the location of the configuration file leading to the NullPointerException. Please try to set up the path for configuration file.

**Comment by singlaabhinandan** [comment] 2020-02-26 19:58
I sent a separate mail with the screenshots, please check if you can see
them there.
Also can you please elaborate on how and where do I need to setup the
configuration file.

**Comment by singlaabhinandan** [comment] 2020-02-26 20:02
https://drive.google.com/open?id=1sMEKwAggFqtvURx7Bfhm3IEaVsv_nRDD

I've uploaded the screenshots on my drive, here's the link to the folder
please let me know if you are able to access them.

**Comment by DNJha** [comment] 2020-02-26 20:12
I can access them now. Can you also send me the screenshot of library and the package explorer with all the packages as I am sure now that the problem is because of configuration file mapping.

Configuration file (configuration.json) is located in src/main/resources which can be mapped directly to the example class but for your case, it is not mapped i.e. the main file cannot find the configuration.json.

**Comment by singlaabhinandan** [comment] 2020-02-26 20:35
I uploaded the SS with the libraries and the package explorer.

**Comment by DNJha** [comment] 2020-02-27 19:23
Since IoTSim-Edge is compiling successfully for you so I am closing this issue.

**Closed as completed by DNJha** 2020-02-27 19:23 UTC
